// @yume-format: 1

export const __block = {
  "id": "readme",
  "type": "aiDoc",
  "schemaVersion": 1,
  "runtime": {
    "name": "yume",
    "version": "002"
  },
  "api": [
    "commit",
    "history",
    "show",
    "validate",
    "exportMarkdown"
  ],
  "versions": [
    {
      "hash": "46641fab99b14ab74b9798bfab85827032c9fe2e86d179be7b60f4562ef770e9",
      "prevHash": null,
      "content": "// README.aiDoc.yume.js - REAL source for README.md\n// This file is the REAL (Axiom A3). README.md is a SHADOW generated from this.\n\nexport const Content = {\n  title: \"yume-develop\",\n  summary: \"yume-develop is the product-track workspace for AI-Native development. It evolves the concepts proven in `ai-desk v2` into the self-contained `.yume.js` (BLOCKFILE) format.\",\n  bootstrap: \"This repository is intentionally self-contained. It is bootstrapped from `ai-desk v2` and the `yume-files` format work, but it does not require a sibling `yume-files` checkout at runtime.\",\n  philosophy: [\n    { name: \"All-as-Block\", detail: \"Functions, constraints, observations, and documentation are all represented as Blocks.\" },\n    { name: \"Versions-as-Body\", detail: \"The true state of a Block is its append-only `versions` array.\" },\n    { name: \"Top-Down E2E-First Verification (Axiom A14)\", detail: \"Testing starts with End-to-End scenarios to establish the 'gravitational field' of context. Unit tests are then autonomously generated by AI to fill coverage gaps identified during E2E execution.\" }\n  ],\n  contents: [\n    { path: \"core.module.yume.js\", desc: \"Core logic for Block and Graph management.\" },\n    { path: \"cli.module.yume.js\", desc: \"The Command Line Interface.\" },\n    { path: \"runtimes/\", desc: \"Co-located yume runtimes.\" },\n    { path: \"bible.aiDoc.yume.js\", desc: \"The canonical philosophy and axioms (including A14).\" },\n    { path: \"onboarding.aiDoc.yume.js\", desc: \"Rules and guidelines for AI agents working in this repo.\" }\n  ],\n  relationship: {\n    aiDesk: \"Research lab and reference implementation.\",\n    yumeFiles: \"Format/spec origin. Treat it as lineage, not a runtime dependency.\",\n    yumeDevelop: \"Mainline product workspace.\"\n  },\n  usage: {\n    commands: [\n      { cmd: \"npm test\", desc: \"Run the complete local suite\" },\n      { cmd: \"npm run test:e2e\", desc: \"Run e2e suite\" },\n      { cmd: \"node runYume.js core.module.yume.js history\", desc: \"List versions of a file\" },\n      { cmd: \"node runYume.js examples/hello.fn.yume.js refs-check .\", desc: \"Check the integrity of the reference graph\" },\n      { cmd: \"node runYume.js <file>.yume.js show head --raw\", desc: \"Extract clean HEAD source from a large yume file\" }\n    ]\n  },\n  completion: [\n    \"Changed .yume.js files validate.\",\n    \"Reference graph changes pass refs-check.\",\n    \"Public docs (SHADOW) are aligned with REAL source.\"\n  ]\n};\n\nexport const exportMarkdown = () => {\n  let md = `# ${Content.title}\\n\\n${Content.summary}\\n\\n${Content.bootstrap}\\n\\n`;\n  \n  md += `## Philosophy\\n\\nCode is history. In yume-develop, every file is a \\`.yume.js\\` file that carries its own entire version history, dependency graph, and metadata within itself.\\n\\n`;\n  md += Content.philosophy.map(p => `- **${p.name}**: ${p.detail}`).join('\\n') + '\\n\\n';\n  \n  md += `## Contents\\n\\n`;\n  md += Content.contents.map(c => `- \\`${c.path}\\`: ${c.desc}`).join('\\n') + '\\n\\n';\n  \n  md += `## Relationship to ai-desk and yume-files\\n\\n`;\n  md += `- **ai-desk**: ${Content.relationship.aiDesk}\\n`;\n  md += `- **yume-files**: ${Content.relationship.yumeFiles}\\n`;\n  md += `- **yume-develop**: ${Content.relationship.yumeDevelop}\\n\\n`;\n  \n  md += `## Usage\\n\\nFiles in this repository are managed through \\`runYume.js\\`, which resolves the runtime pinned by each \\`.yume.js\\` file.\\n\\n\\`\\`\\`bash\\n`;\n  md += Content.usage.commands.map(c => `# ${c.desc}\\n${c.cmd}`).join('\\n\\n') + '\\n```\\n\\n';\n  \n  md += `## Completion Standard\\n\\n`;\n  md += Content.completion.map(c => `- ${c}`).join('\\n') + '\\n';\n  \n  return md;\n};\n",
      "ts": 1778951598747,
      "refs": [],
      "tags": [],
      "applyId": null
    },
    {
      "hash": "c516cb38078408c79244502029dc10bc618ccf3d1d9f59b1ba2ded02dac8cdc5",
      "prevHash": "46641fab99b14ab74b9798bfab85827032c9fe2e86d179be7b60f4562ef770e9",
      "content": "// README.aiDoc.yume.js - REAL source for README.md\n// This file is the REAL (Axiom A3). README.md is a SHADOW generated from this.\n\nexport const Content = {\n  title: \"yume-develop\",\n  summary: \"yume-develop is a workspace and reference implementation for AI-Native development. It evolves the concepts proven in `ai-desk v2` into the self-contained `.yume.js` (BLOCKFILE) format.\",\n  bootstrap: \"This repository is intentionally self-contained. It is bootstrapped from `ai-desk v2` and the `yume-files` format work, but it does not require a sibling `yume-files` checkout at runtime.\",\n  philosophy: [\n    { name: \"All-as-Block\", detail: \"Functions, constraints, observations, and documentation are all represented as Blocks.\" },\n    { name: \"Versions-as-Body\", detail: \"The true state of a Block is its append-only `versions` array.\" },\n    { name: \"Top-Down E2E-First Verification (Axiom A14)\", detail: \"Testing starts with End-to-End scenarios to establish the 'gravitational field' of context. Unit tests are then autonomously generated by AI to fill coverage gaps identified during E2E execution.\" }\n  ],\n  contents: [\n    { path: \"core.module.yume.js\", desc: \"Core logic for Block and Graph management.\" },\n    { path: \"cli.module.yume.js\", desc: \"The Command Line Interface.\" },\n    { path: \"runtimes/\", desc: \"Co-located yume runtimes.\" },\n    { path: \"bible.aiDoc.yume.js\", desc: \"The canonical philosophy and axioms (including A14).\" },\n    { path: \"onboarding.aiDoc.yume.js\", desc: \"Rules and guidelines for AI agents working in this repo.\" }\n  ],\n  relationship: {\n    aiDesk: \"Research lab and reference implementation.\",\n    yumeFiles: \"Format/spec origin. Treat it as lineage, not a runtime dependency.\",\n    yumeDevelop: \"Mainline development workspace and reference library.\"\n  },\n  usage: {\n    commands: [\n      { cmd: \"npm test\", desc: \"Run the complete local suite\" },\n      { cmd: \"npm run test:e2e\", desc: \"Run e2e suite\" },\n      { cmd: \"node runYume.js core.module.yume.js history\", desc: \"List versions of a file\" },\n      { cmd: \"node runYume.js examples/hello.fn.yume.js refs-check .\", desc: \"Check the integrity of the reference graph\" },\n      { cmd: \"node runYume.js <file>.yume.js show head --raw\", desc: \"Show clean HEAD source without embedded history\" }\n    ]\n  },\n  completion: [\n    \"Changed .yume.js files validate.\",\n    \"Reference graph changes pass refs-check.\",\n    \"Public docs (SHADOW) are aligned with REAL source.\"\n  ]\n};\n\nexport const exportMarkdown = () => {\n  let md = `# ${Content.title}\\n\\n${Content.summary}\\n\\n${Content.bootstrap}\\n\\n`;\n  \n  md += `## Philosophy\\n\\nCode is history. In yume-develop, every file is a \\`.yume.js\\` file that carries its own entire version history, dependency graph, and metadata within itself.\\n\\n`;\n  md += Content.philosophy.map(p => `- **${p.name}**: ${p.detail}`).join('\\n') + '\\n\\n';\n  \n  md += `## Contents\\n\\n`;\n  md += Content.contents.map(c => `- \\`${c.path}\\`: ${c.desc}`).join('\\n') + '\\n\\n';\n  \n  md += `## Relationship to ai-desk and yume-files\\n\\n`;\n  md += `- **ai-desk**: ${Content.relationship.aiDesk}\\n`;\n  md += `- **yume-files**: ${Content.relationship.yumeFiles}\\n`;\n  md += `- **yume-develop**: ${Content.relationship.yumeDevelop}\\n\\n`;\n  \n  md += `## Usage\\n\\nFiles in this repository are managed through \\`runYume.js\\`, which resolves the runtime pinned by each \\`.yume.js\\` file.\\n\\n\\`\\`\\`bash\\n`;\n  md += Content.usage.commands.map(c => `# ${c.desc}\\n${c.cmd}`).join('\\n\\n') + '\\n```\\n\\n';\n  \n  md += `## Completion Standard\\n\\n`;\n  md += Content.completion.map(c => `- ${c}`).join('\\n') + '\\n';\n  \n  return md;\n};\n",
      "ts": 1778951736119,
      "refs": [],
      "tags": [],
      "applyId": "apply-2026-05-16-243749dc"
    },
    {
      "content": "// README.aiDoc.yume.js - REAL source for README.md\n// This file is the REAL (Axiom A3). README.md is a SHADOW generated from this.\n\nexport const Content = {\n  title: \"yume-develop\",\n  summary: \"yume-develop is a workspace and reference implementation for AI-Native development. It evolves the concepts proven in `ai-desk v2` into the self-contained `.yume.js` (BLOCKFILE) format.\",\n  bootstrap: \"This repository is intentionally self-contained. It is bootstrapped from `ai-desk v2` and the `yume-files` format work, but it does not require a sibling `yume-files` checkout at runtime.\",\n  philosophy: [\n    { name: \"All-as-Block\", detail: \"Functions, constraints, observations, and documentation are all represented as Blocks.\" },\n    { name: \"Versions-as-Body\", detail: \"The true state of a Block is its append-only `versions` array.\" },\n    { name: \"Top-Down E2E-First Verification (Axiom A14)\", detail: \"Testing starts with End-to-End scenarios to establish the 'gravitational field' of context. Unit tests are then autonomously generated by AI to fill coverage gaps identified during E2E execution.\" }\n  ],\n  contents: [\n    { path: \"core.module.yume.js\", desc: \"Core logic for Block and Graph management.\" },\n    { path: \"cli.module.yume.js\", desc: \"The Command Line Interface.\" },\n    { path: \"runtimes/\", desc: \"Co-located yume runtimes.\" },\n    { path: \"bible.aiDoc.yume.js\", desc: \"The canonical philosophy and axioms (including A14).\" },\n    { path: \"onboarding.aiDoc.yume.js\", desc: \"Rules and guidelines for AI agents working in this repo.\" }\n  ],\n  relationship: {\n    aiDesk: \"Research lab and reference implementation.\",\n    yumeFiles: \"Format/spec origin. Treat it as lineage, not a runtime dependency.\",\n    yumeDevelop: \"Mainline development workspace and reference library.\"\n  },\n  usage: {\n    commands: [\n      { cmd: \"npm test\", desc: \"Run the complete local suite\" },\n      { cmd: \"npm run test:e2e\", desc: \"Run e2e suite\" },\n      { cmd: \"node runYume.js core.module.yume.js history\", desc: \"List versions of a file\" },\n      { cmd: \"npm run refs-check\", desc: \"Check the integrity of the reference graph\" },\n      { cmd: \"node runYume.js <file>.yume.js show head --raw\", desc: \"Show clean HEAD source without embedded history\" }\n    ]\n  },\n  completion: [\n    \"Changed .yume.js files validate.\",\n    \"Reference graph changes pass refs-check.\",\n    \"Public docs (SHADOW) are aligned with REAL source.\"\n  ]\n};\n\nexport const exportMarkdown = () => {\n  let md = `# ${Content.title}\\n\\n${Content.summary}\\n\\n${Content.bootstrap}\\n\\n`;\n  \n  md += `## Philosophy\\n\\nCode is history. In yume-develop, every file is a \\`.yume.js\\` file that carries its own entire version history, dependency graph, and metadata within itself.\\n\\n`;\n  md += Content.philosophy.map(p => `- **${p.name}**: ${p.detail}`).join('\\n') + '\\n\\n';\n  \n  md += `## Contents\\n\\n`;\n  md += Content.contents.map(c => `- \\`${c.path}\\`: ${c.desc}`).join('\\n') + '\\n\\n';\n  \n  md += `## Relationship to ai-desk and yume-files\\n\\n`;\n  md += `- **ai-desk**: ${Content.relationship.aiDesk}\\n`;\n  md += `- **yume-files**: ${Content.relationship.yumeFiles}\\n`;\n  md += `- **yume-develop**: ${Content.relationship.yumeDevelop}\\n\\n`;\n  \n  md += `## Usage\\n\\nFiles in this repository are managed through \\`runYume.js\\`, which resolves the runtime pinned by each \\`.yume.js\\` file.\\n\\n\\`\\`\\`bash\\n`;\n  md += Content.usage.commands.map(c => `# ${c.desc}\\n${c.cmd}`).join('\\n\\n') + '\\n```\\n\\n';\n  \n  md += `## Completion Standard\\n\\n`;\n  md += Content.completion.map(c => `- ${c}`).join('\\n') + '\\n';\n  \n  return md;\n};\n",
      "ts": 1779864451602,
      "refs": [],
      "tags": [],
      "applyId": "apply-2026-05-27-ffaf3593",
      "hash": "049ea8e36cecdf6c3bc1c2ea72763e6fb1a678efe67a2087a40584e32ff026f8",
      "prevHash": "c516cb38078408c79244502029dc10bc618ccf3d1d9f59b1ba2ded02dac8cdc5"
    }
  ],
  "notes": {
    "46641fab99b14ab74b9798bfab85827032c9fe2e86d179be7b60f4562ef770e9": [
      {
        "id": "note-46641fab99b1",
        "ts": 1778951598747,
        "author": "ai",
        "kind": "repair",
        "text": "repair noncanonical __block JSON and align README commands with runYume dispatcher"
      }
    ],
    "apply:apply-2026-05-16-243749dc": [
      {
        "id": "n-7df46ef8-7205-4ef9-a90c-c5791ef64c63",
        "author": "ai",
        "ts": 1778951736122,
        "text": "align REAL README source with generated README text",
        "kind": "repair"
      }
    ],
    "apply:apply-2026-05-27-ffaf3593": [
      {
        "id": "n-1716df7d-ebfb-4f41-9c20-3514a2e997a1",
        "author": "human",
        "ts": 1779864451605,
        "text": "Use npm refs-check as the canonical graph check"
      }
    ]
  }
};

// === HEAD ===
// README.aiDoc.yume.js - REAL source for README.md
// This file is the REAL (Axiom A3). README.md is a SHADOW generated from this.

export const Content = {
  title: "yume-develop",
  summary: "yume-develop is a workspace and reference implementation for AI-Native development. It evolves the concepts proven in `ai-desk v2` into the self-contained `.yume.js` (BLOCKFILE) format.",
  bootstrap: "This repository is intentionally self-contained. It is bootstrapped from `ai-desk v2` and the `yume-files` format work, but it does not require a sibling `yume-files` checkout at runtime.",
  philosophy: [
    { name: "All-as-Block", detail: "Functions, constraints, observations, and documentation are all represented as Blocks." },
    { name: "Versions-as-Body", detail: "The true state of a Block is its append-only `versions` array." },
    { name: "Top-Down E2E-First Verification (Axiom A14)", detail: "Testing starts with End-to-End scenarios to establish the 'gravitational field' of context. Unit tests are then autonomously generated by AI to fill coverage gaps identified during E2E execution." }
  ],
  contents: [
    { path: "core.module.yume.js", desc: "Core logic for Block and Graph management." },
    { path: "cli.module.yume.js", desc: "The Command Line Interface." },
    { path: "runtimes/", desc: "Co-located yume runtimes." },
    { path: "bible.aiDoc.yume.js", desc: "The canonical philosophy and axioms (including A14)." },
    { path: "onboarding.aiDoc.yume.js", desc: "Rules and guidelines for AI agents working in this repo." }
  ],
  relationship: {
    aiDesk: "Research lab and reference implementation.",
    yumeFiles: "Format/spec origin. Treat it as lineage, not a runtime dependency.",
    yumeDevelop: "Mainline development workspace and reference library."
  },
  usage: {
    commands: [
      { cmd: "npm test", desc: "Run the complete local suite" },
      { cmd: "npm run test:e2e", desc: "Run e2e suite" },
      { cmd: "node runYume.js core.module.yume.js history", desc: "List versions of a file" },
      { cmd: "npm run refs-check", desc: "Check the integrity of the reference graph" },
      { cmd: "node runYume.js <file>.yume.js show head --raw", desc: "Show clean HEAD source without embedded history" }
    ]
  },
  completion: [
    "Changed .yume.js files validate.",
    "Reference graph changes pass refs-check.",
    "Public docs (SHADOW) are aligned with REAL source."
  ]
};

export const exportMarkdown = () => {
  let md = `# ${Content.title}\n\n${Content.summary}\n\n${Content.bootstrap}\n\n`;
  
  md += `## Philosophy\n\nCode is history. In yume-develop, every file is a \`.yume.js\` file that carries its own entire version history, dependency graph, and metadata within itself.\n\n`;
  md += Content.philosophy.map(p => `- **${p.name}**: ${p.detail}`).join('\n') + '\n\n';
  
  md += `## Contents\n\n`;
  md += Content.contents.map(c => `- \`${c.path}\`: ${c.desc}`).join('\n') + '\n\n';
  
  md += `## Relationship to ai-desk and yume-files\n\n`;
  md += `- **ai-desk**: ${Content.relationship.aiDesk}\n`;
  md += `- **yume-files**: ${Content.relationship.yumeFiles}\n`;
  md += `- **yume-develop**: ${Content.relationship.yumeDevelop}\n\n`;
  
  md += `## Usage\n\nFiles in this repository are managed through \`runYume.js\`, which resolves the runtime pinned by each \`.yume.js\` file.\n\n\`\`\`bash\n`;
  md += Content.usage.commands.map(c => `# ${c.desc}\n${c.cmd}`).join('\n\n') + '\n```\n\n';
  
  md += `## Completion Standard\n\n`;
  md += Content.completion.map(c => `- ${c}`).join('\n') + '\n';
  
  return md;
};

// === /HEAD ===
